'use client';

import CustomerList from './components/CustomerList';
import { Customer, CustomerProgress, Achievements } from '@/lib/types/customer';

// 더미 데이터 생성 함수
function createDummyCustomers(): Customer[] {
  return [
    {
      id: 'dummy-1',
      kol_id: 1,
      name: '김미영 원장님',
      shopName: '뷰티살롱 A',
      phone: '010-1234-5678',
      region: '서울 강남구',
      placeAddress: '서울시 강남구 역삼동 123-45',
      assignee: '이영희',
      manager: '박철수',
      status: 'active',
      notes: '',
      completed_stages: 3,
      total_stages: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      customer_progress: [
        {
          id: 'progress-1',
          customerId: 'dummy-1',
          stageData: {
            inflow: { source: 'cafe', memo: '' },
            contract: {
              type: 'purchase',
              purchaseDate: '2024-01-15',
              purchaseAmount: '500',
              memo: '',
            },
            delivery: {
              type: 'install',
              installDate: '2024-01-20',
              installContactName: '김설치',
              installContactPhone: '010-9999-8888',
              memo: '',
            },
            educationNotes: {
              q1Level: '상',
              q1YN: true,
              q2Level: '중',
              q2YN: true,
              q3Level: '상',
              q3YN: true,
              q4Level: '상',
              q4YN: true,
              q5Level: '중',
              q6Level: '상',
              personality: ['긍정형'],
              memo: '',
            },
            growth: {
              clinicalProgress: { personal: 7, customers: [3, 2, 3, 1, 2, 0, 0, 0, 0, 0] },
              learningProgress: {
                홍조: { value: 6, max: 8, label: '홍조' },
                기미: { value: 8, max: 12, label: '기미' },
                브리핑: { value: 4, max: 6, label: '브리핑' },
                여드름: { value: 5, max: 8, label: '여드름' },
              },
              evaluationScores: {
                '모의 테스트': 85,
                '실전 테스트': 90,
              },
              salesData: [320, 380, 450, 480, 520, 580, 610, 650, 680, 720, 750, 800],
            },
            expert: { topic: '매출업', memo: '' },
          } as any,
          achievements: {
            basicTraining: true,
            standardProtocol: true,
            expertCourse: false,
            starManager: true,
            starOwner: true,
            starDirector: false,
            clinicalStar: true,
            learningStar: true,
            expertOwner: false,
            expertEducator: false,
          },
          updatedAt: new Date().toISOString(),
        },
      ],
    },
    {
      id: 'dummy-2',
      kol_id: 1,
      name: '박소연 대표님',
      shopName: '헤어샵 B',
      phone: '010-2345-6789',
      region: '서울 서초구',
      placeAddress: '서울시 서초구 방배동 456-78',
      assignee: '김지원',
      manager: '최민수',
      status: 'active',
      notes: '',
      completed_stages: 2,
      total_stages: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      customer_progress: [
        {
          id: 'progress-2',
          customerId: 'dummy-2',
          stageData: {
            inflow: { source: 'insta', memo: '인스타그램 광고를 통해 유입' },
            contract: {
              type: 'deposit',
              depositDate: '2024-02-01',
              depositAmount: '100',
              memo: '',
            },
            delivery: {},
            educationNotes: {},
            growth: {},
            expert: {},
          } as any,
          achievements: {
            basicTraining: false,
            standardProtocol: false,
            expertCourse: false,
            starManager: false,
            starOwner: false,
            starDirector: false,
            clinicalStar: false,
            learningStar: false,
            expertOwner: false,
            expertEducator: false,
          },
          updatedAt: new Date().toISOString(),
        },
      ],
    },
    {
      id: 'dummy-3',
      kol_id: 1,
      name: '이정희 원장님',
      shopName: '스킨케어 C',
      phone: '010-3456-7890',
      region: '경기 성남시',
      placeAddress: '경기도 성남시 분당구 정자동 789-12',
      assignee: '정수민',
      manager: '강민정',
      status: 'active',
      notes: '',
      completed_stages: 5,
      total_stages: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      customer_progress: [
        {
          id: 'progress-3',
          customerId: 'dummy-3',
          stageData: {
            inflow: { source: 'intro', memo: '기존 고객 소개' },
            contract: {
              type: 'purchase',
              purchaseDate: '2023-12-10',
              purchaseAmount: '800',
              memo: '',
            },
            delivery: {
              type: 'install',
              installDate: '2023-12-15',
              installContactName: '박기술',
              installContactPhone: '010-7777-6666',
              memo: '',
            },
            educationNotes: {
              q1Level: '상',
              q1YN: true,
              q2Level: '상',
              q2YN: true,
              q3Level: '상',
              q3YN: true,
              q4Level: '상',
              q4YN: true,
              q5Level: '상',
              q6Level: '상',
              personality: ['긍정형', '학습부족형'],
              memo: '매우 열정적이고 빠르게 습득함',
            },
            growth: {
              clinicalProgress: { personal: 10, customers: [3, 3, 3, 3, 3, 3, 2, 2, 1, 1] },
              learningProgress: {
                홍조: { value: 8, max: 8, label: '홍조' },
                기미: { value: 12, max: 12, label: '기미' },
                브리핑: { value: 6, max: 6, label: '브리핑' },
                여드름: { value: 8, max: 8, label: '여드름' },
              },
              evaluationScores: {
                '모의 테스트': 95,
                '실전 테스트': 98,
              },
              salesData: [500, 550, 600, 680, 750, 820, 900, 980, 1050, 1100, 1150, 1200],
            },
            expert: {},
          } as any,
          achievements: {
            basicTraining: true,
            standardProtocol: true,
            expertCourse: false,
            starManager: true,
            starOwner: true,
            starDirector: true,
            clinicalStar: true,
            learningStar: true,
            expertOwner: false,
            expertEducator: false,
          },
          updatedAt: new Date().toISOString(),
        },
      ],
    },
    {
      id: 'dummy-4',
      kol_id: 1,
      name: '최은정 대표님',
      shopName: '네일아트 D',
      phone: '010-4567-8901',
      region: '서울 송파구',
      placeAddress: '서울시 송파구 잠실동 345-67',
      assignee: '홍길동',
      manager: '이순신',
      status: 'active',
      notes: 'VIP 고객',
      completed_stages: 6,
      total_stages: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      customer_progress: [
        {
          id: 'progress-4',
          customerId: 'dummy-4',
          stageData: {
            inflow: {
              source: 'seminar',
              seminarDate: '2023-10-15',
              seminarCount: '2',
              memo: '세미나 참석 후 즉시 계약',
            },
            contract: {
              type: 'purchase',
              purchaseDate: '2023-10-16',
              purchaseAmount: '1200',
              memo: 'VIP 패키지',
            },
            delivery: {
              type: 'ship',
              shipDate: '2023-10-20',
              shipPackage: '프리미엄 패키지',
              memo: '',
            },
            educationNotes: {
              q1Level: '상',
              q1YN: true,
              q2Level: '상',
              q2YN: true,
              q3Level: '상',
              q3YN: true,
              q4Level: '상',
              q4YN: true,
              q5Level: '상',
              q6Level: '상',
              personality: ['긍정형'],
              memo: '모든 면에서 우수한 고객',
            },
            growth: {
              clinicalProgress: { personal: 10, customers: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3] },
              learningProgress: {
                홍조: { value: 8, max: 8, label: '홍조' },
                기미: { value: 12, max: 12, label: '기미' },
                브리핑: { value: 6, max: 6, label: '브리핑' },
                여드름: { value: 8, max: 8, label: '여드름' },
              },
              evaluationScores: {
                '모의 테스트': 100,
                '실전 테스트': 100,
              },
              salesData: [800, 850, 900, 950, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700],
            },
            expert: { topic: '매출업', memo: '전문가 과정 이수 완료' },
          } as any,
          achievements: {
            basicTraining: true,
            standardProtocol: true,
            expertCourse: true,
            starManager: true,
            starOwner: true,
            starDirector: true,
            clinicalStar: true,
            learningStar: true,
            expertOwner: true,
            expertEducator: true,
          },
          updatedAt: new Date().toISOString(),
        },
      ],
    },
    {
      id: 'dummy-5',
      kol_id: 1,
      name: '정현주 사장님',
      shopName: '메이크업 스튜디오 E',
      phone: '010-5678-9012',
      region: '경기 수원시',
      placeAddress: '경기도 수원시 영통구 매탄동 123-45',
      assignee: '박지민',
      manager: '김태희',
      status: 'active',
      notes: '',
      completed_stages: 1,
      total_stages: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      customer_progress: [
        {
          id: 'progress-5',
          customerId: 'dummy-5',
          stageData: {
            inflow: {
              source: 'visit',
              visitDate: '2024-03-01',
              visitCount: '1',
              memo: '직접 방문하여 상담',
            },
            contract: {
              type: 'reject',
              rejectDate: '2024-03-05',
              rejectReason: '예산 부족',
              rejectAd: true,
              rejectRetarget: true,
              memo: '',
            },
            delivery: {},
            educationNotes: {},
            growth: {},
            expert: {},
          } as any,
          achievements: {
            basicTraining: false,
            standardProtocol: false,
            expertCourse: false,
            starManager: false,
            starOwner: false,
            starDirector: false,
            clinicalStar: false,
            learningStar: false,
            expertOwner: false,
            expertEducator: false,
          },
          updatedAt: new Date().toISOString(),
        },
      ],
    },
  ];
}

export default function CustomerManagerClient() {
  // 인증 체크 제거, 더미 데이터 사용
  const dummyCustomers = createDummyCustomers();
  const dummyKolId = 'dummy-kol-id';

  return (
    <div className="mx-auto w-full px-0">
      <CustomerList initialData={dummyCustomers} kolId={dummyKolId} />
    </div>
  );
}
