name: 🚀 Convex Deployment Pipeline

on:
  push:
    branches: [ main, develop, convex ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

# 동시에 하나의 배포만 실행되도록 설정
concurrency:
  group: convex-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # 코드 품질 및 테스트
  quality-check:
    name: 🔍 Quality & Testing
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      - name: ⚡ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: 📦 Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            .next/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-
            
      - name: 📚 Install dependencies
        run: npm ci
        
      - name: 🔧 TypeScript type check
        run: npx tsc --noEmit
        
      - name: 🎨 Lint code
        run: npm run lint
        
      - name: 🧪 Run unit tests
        run: npm run test
        
      - name: 🏗️ Build application
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: true
          
  # Convex 함수 유효성 검사
  convex-validation:
    name: 🔮 Convex Functions Validation
    runs-on: ubuntu-latest
    needs: quality-check
    timeout-minutes: 10
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      - name: ⚡ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: 📚 Install dependencies
        run: npm ci
        
      - name: 🔍 Validate Convex functions
        run: npm run test:convex
        working-directory: ./
          
  # Preview 배포 (PR용)
  deploy-preview:
    name: 🌟 Deploy Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [quality-check, convex-validation]
    timeout-minutes: 10
    
    environment:
      name: preview
      url: ${{ steps.preview-deploy.outputs.deployment-url }}
      
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      - name: ⚡ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: 📚 Install dependencies
        run: npm ci
        
             - name: 🚀 Deploy to Convex Preview
         id: preview-deploy
         run: |
           npm run deploy:preview
           echo "deployment-url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
         env:
           CONVEX_PREVIEW_DEPLOYMENT_KEY: ${{ secrets.CONVEX_PREVIEW_DEPLOY_KEY }}
           DEPLOYMENT_URL: ""
          
      - name: 💬 Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🌟 **Preview deployment ready!**\n\n📱 Preview URL: ${{ steps.preview-deploy.outputs.deployment-url }}\n\n⚡ Deployment ID: \`${{ github.run_id }}\``
            })
            
  # 스테이징 배포 (develop 브랜치)
  deploy-staging:
    name: 🧪 Deploy Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    needs: [quality-check, convex-validation]
    timeout-minutes: 15
    
    environment:
      name: staging
      url: ${{ steps.staging-deploy.outputs.deployment-url }}
      
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      - name: ⚡ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: 📚 Install dependencies
        run: npm ci
        
      - name: 🧪 Run comprehensive tests
        run: |
          npm run test
          npm run test:e2e
        env:
          # 스테이징 테스트 환경변수
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.STAGING_CONVEX_URL }}
          
             - name: 🚀 Deploy to Convex Staging
         id: staging-deploy
         run: |
           npm run deploy:staging
           echo "deployment-url=$CONVEX_STAGING_URL" >> $GITHUB_OUTPUT
         env:
           CONVEX_STAGING_DEPLOYMENT_KEY: ${{ secrets.CONVEX_STAGING_DEPLOY_KEY }}
           CONVEX_STAGING_URL: ${{ secrets.CONVEX_STAGING_URL }}
          
      - name: ✅ Verify staging deployment
        run: node scripts/verify-deployment.js
        env:
          DEPLOYMENT_URL: ${{ steps.staging-deploy.outputs.deployment-url }}
          VERIFICATION_TIMEOUT: 60000
          
  # 프로덕션 배포 (main 브랜치)
  deploy-production:
    name: 🚀 Deploy Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [quality-check, convex-validation]
    timeout-minutes: 20
    
    environment:
      name: production
      url: ${{ steps.production-deploy.outputs.deployment-url }}
      
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      - name: ⚡ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: 📚 Install dependencies
        run: npm ci
        
      - name: 🧪 Final testing before production
        run: |
          npm run test
          npm run lint
          npx tsc --noEmit
          
             - name: 🚀 Deploy to Convex Production
         id: production-deploy
         run: |
           npm run deploy
           echo "deployment-url=$CONVEX_URL" >> $GITHUB_OUTPUT
         env:
           CONVEX_DEPLOYMENT_KEY: ${{ secrets.CONVEX_PRODUCTION_DEPLOY_KEY }}
           CONVEX_URL: ${{ secrets.CONVEX_URL }}
           NODE_ENV: production
          
  # 배포 알림
  notify-deployment:
    name: 📢 Deployment Notification
    runs-on: ubuntu-latest
    if: always() && (needs.deploy-staging.result != 'skipped' || needs.deploy-production.result != 'skipped')
    needs: [deploy-staging, deploy-production]
    
    steps:
      - name: 🎉 Success notification
        if: ${{ needs.deploy-staging.result == 'success' || needs.deploy-production.result == 'success' }}
        run: |
          echo "✅ Deployment completed successfully!"
          echo "Environment: ${{ needs.deploy-staging.result == 'success' && 'Staging' || 'Production' }}"
          echo "Commit: ${{ github.sha }}"
          
      - name: ❌ Failure notification
        if: ${{ needs.deploy-staging.result == 'failure' || needs.deploy-production.result == 'failure' }}
        run: |
          echo "❌ Deployment failed!"
          echo "Environment: ${{ needs.deploy-staging.result == 'failure' && 'Staging' || 'Production' }}"
          echo "Commit: ${{ github.sha }}"
          echo "Please check the deployment logs and fix the issues." 